# WordPress Secret
apiVersion: v1
kind: Secret
metadata:
    name: wordpress-secret
    namespace: wordpress-namespace
type: Opaque
data:
    #ENC[AES256_GCM,data:T09ikDzlveyH0zJXDk9fGniYR1nlSQ==,iv:4O1Hgu1WJAsSWZa8GBCvBkIt2eshK4UUBMQuNjRaWgg=,tag:EJKEG9xk4yyZQDtnT1m8Kw==,type:comment]
    WORDPRESS_DB_PASSWORD: ENC[AES256_GCM,data:cinDXrGO7EWrRVj5,iv:dq4nSaPmCSspPG+YZpscIC3gxRiy/ULDARfj7BHeNs8=,tag:7XdV6/vxaC5bWvwMEYyVdw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/planar-airship-434723-g8/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-09T16:30:31Z"
          enc: CiQAA9WKfnoMv9WaA9g3y8DjrCauKmp0cwuSaSphNNoduYJbZ2YSSQANPnGVVV9sdnYiuKAZjLEMtu//3DwA/PjPXm79o1yP/Q3tMTMChH/uXVC2/flqg9mRDCvsAciM5bJngmQ2qoE5ff+K+Q59iOY=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-09T16:30:32Z"
    mac: ENC[AES256_GCM,data:nbopXlP334W1R91R60ifT6q9iLio2oozn9GMljr/4pisBM/xEVnWL7DrydWpM9PLvVDRe+o1HG8ndSbYOtWGZkSqRVm7gy12pAIUD3j9sA3sL+aQGNCIgCdVEZy3nkUJptwCzAjGeFw64vhN3JBhL4tUCZAKnRdZtalrX8I3V04=,iv:J5aM9PvHJMnL8RWFi2S1bq45nNhTz+XbjB3MFwcNLT4=,tag:WG/B+XmVR1sMYONco3/MwA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
