# WordPress Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: wordpress-namespace
---
# WordPress ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: wordpress-namespace
data:
  WORDPRESS_DB_HOST: db
---
# WordPress Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wordpress-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: gcr.io/planar-airship-434723-g8/wordpress:latest
          envFrom:
            - configMapRef:
                name: wordpress-config
            - secretRef:
                name: wordpress-secret
          ports:
            - containerPort: 80
---
# WordPress Service
apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-namespace
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
